- defaults:
    link:
        create: true
        relink: true

- clean:
        - '~'
        - ~/.cargo
        - ~/.config
        - ~/.ssh

- shell:
        - mkdir -p ~/.cargo
        - mkdir -p ~/.config
        - mkdir -p ~/.ssh
        - mkdir -p ~/.vim/autoload

- link:
        ~/app: app

        ~/.bash_profile:                        etc/bash_profile
        ~/.bashrc:                              etc/bashrc
        ~/.config/git/config:                   etc/gitconfig
        ~/.profile:                             etc/profile
        ~/.tmux.conf:                           etc/tmux.conf
        ~/.vim/autoload/plug.vim:               submodules/vim-plug/plug.vim
        ~/.vimrc:                               etc/vimrc
