- defaults:
    link:
        create: true
        relink: true

- clean:
        - '~'
        - ~/.cargo
        - ~/.config

- shell:
        - mkdir -p ~/.cargo
        - mkdir -p ~/.config
        - mkdir -p ~/.config/nvim

- link:

        ~/.config/git/config:                   etc/gitconfig
        ~/.tmux.conf:                           etc/tmux.conf
        ~/.config/nvim/init.vim:                etc/nvim/init.vim
        ~/.zshrc:                               etc/zshrc
