- defaults:
    link:
        create: true
        relink: true

- clean:
        - '~'
        - ~/.cargo
        - ~/.config
        - ~/.ssh

- shell:
        - mkdir -p ~/aur
        - mkdir -p ~/.cargo
        - mkdir -p ~/.config
        - mkdir -p ~/.config/alacritty
        - mkdir -p ~/.config/i3config
        - mkdir -p ~/.gnupg
        - mkdir -p ~/.local/share/lpass
        - mkdir -p ~/.ssh

- link:
        ~/app: app

        ~/.config/alacritty/alacritty.yml:      etc/alacritty.yml
        ~/.config/git/config:                   etc/gitconfig
        ~/.config/i3/config:                    etc/i3config
        ~/.config/.secrets:                     etc/secrets
        ~/.ssh/config:                          etc/ssh-config
        ~/.secrets:                             etc/secrets
        ~/.config/nvim/init.vim:                etc/nvim/init.vim
        ~/.tmux.conf:                           etc/tmux.conf
        ~/.xinitrc:                             etc/xinitrc
        ~/.xresources:                          etc/xresources
        ~/.zshrc:                               etc/zshrc
        ~/.zshenv:                              etc/zshenv
