- defaults:
    link:
        create: true
        relink: true

- clean:
        - '~'
        - ~/.cargo
        - ~/.config
        - ~/.ssh

- shell:
        - mkdir -p ~/.cargo
        - mkdir -p ~/.config
        - mkdir -p ~/.ssh
        - mkdir -p ~/.vim/autoload
        - mkdir -p ~/.vim/colors

- link:
        ~/.bash_profile:                        etc/bash_profile
        ~/.bashrc:                              etc/bashrc
        ~/.profile:                             etc/profile
        ~/.tmux.conf:                           etc/tmux.conf
        ~/.vim/autoload/plug.vim:               submodules/vim-plug/plug.vim
        ~/.vim/colors/codedark.vim:             etc/vim-colors/codedark.vim
        ~/.vimrc:                               etc/vimrc
        

