- defaults:
    link:
        create: true
        relink: true

- clean:
        - '~'
        - ~/.cargo
        - ~/.config
        - ~/.ssh

- shell:
        - mkdir -p ~/aur
        - mkdir -p ~/.cargo
        - mkdir -p ~/.config
        - mkdir -p ~/.config/alacritty
        - mkdir -p ~/.config/i3config
        - mkdir -p ~/.gnupg
        - mkdir -p ~/.local/share/lpass
        - mkdir -p ~/.ssh
        - mkdir -p ~/.vim/autoload

- link:
        ~/app: app

        ~/.bash_profile:                        etc/bash_profile
        ~/.bashrc:                              etc/bashrc
        ~/.config/alacritty/alacritty.yml:      etc/alacritty.yml
        ~/.config/git/config:                   etc/gitconfig
        ~/.config/i3/config:                    etc/i3config
        ~/.profile:                             etc/profile
        ~/.secrets:                             etc/secrets
        ~/.ssh/config:                          etc/ssh-config
        ~/.secrets:                             etc/secrets
        ~/.tmux.conf:                           etc/tmux.conf
        ~/.vim/autoload/plug.vim:               submodules/vim-plug/plug.vim
        ~/.vim/colors/codedark.vim:             etc/vim-colors/codedark.vim
        ~/.vim/colors/jay.vim:                  etc/vim-colors/jay.vim
        ~/.vim/colors/Dark2.vim:                etc/vim-colors/Dark2.vim
        ~/.vim/colors/molokai.vim:              etc/vim-colors/molokai.vim
        ~/.vimrc:                               etc/vimrc
        ~/.xinitrc:                             etc/xinitrc
        ~/.xresources:                          etc/xresources
